[book]
title = "Advent of Code"
authors = ["Gotoki no Joe (Translation)"]
language = "ja"
multilingual = false
src = "src"

[build]
build-dir = "docs"

[output.html]
fold.enable = true
mathjax-support = true
